[providers]
php = "8.2"

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "npm ci && npm run build"
]

[phases.deploy]
cmds = [
    "php artisan migrate --force"
]

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
CACHE_STORE = "database"
SESSION_DRIVER = "database"
QUEUE_CONNECTION = "database"
FILESYSTEM_DISK = "local"
MAIL_MAILER = "log"
BROADCAST_CONNECTION = "log"
APP_LOCALE = "es"
APP_FALLBACK_LOCALE = "es"

# Variables vacías para evitar warnings
DB_CACHE_CONNECTION = ""
AWS_BUCKET = ""
DB_CACHE_LOCK_CONNECTION = ""
DB_CACHE_LOCK_TABLE = ""
AWS_URL = ""
MEMCACHED_PERSISTENT_ID = ""
MEMCACHED_USERNAME = ""
AWS_ENDPOINT = ""
MEMCACHED_PASSWORD = ""
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
LOG_SLACK_WEBHOOK_URL = ""
DYNAMODB_ENDPOINT = ""
MAIL_LOG_CHANNEL = ""
DB_URL = ""
PAPERTRAIL_URL = ""
DB_QUEUE_CONNECTION = ""
PAPERTRAIL_PORT = ""
SESSION_DOMAIN = ""
LOG_STDERR_FORMATTER = ""
MAIL_SCHEME = ""
SQS_SUFFIX = ""
MAIL_URL = ""
POSTMARK_TOKEN = ""
SESSION_SECURE_COOKIE = ""
